# Docker Compose Keycloak Postgres ( Docker compose for Keycloak with Postgres Database).
version: '3.1'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
    ports: 
      - '5432:5432'

  keycloak:
    image: jboss/keycloak:16.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: test_ispirt
      KEYCLOAK_PASSWORD: test_ispirt@123
      PROXY_ADDRESS_FORWARDING: 'true'
      PROXY: 'edge'
      KC_HTTP_RELATIVE_PATH: '/auth'
    restart: unless-stopped
    volumes:
      - ./keycloak/themes/custom:/opt/jboss/keycloak/themes/custom
  #       #- ./keycloak/scripts/disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - postgres

  backend:
    build:
      context: .
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_USERNAME: keycloak
      TYPEORM_PASSWORD: password
      TYPEORM_HOST: postgres
      TYPEORM_DATABASE: keycloak
      TYPEORM_PORT: 5432

    depends_on:
      - postgres
    ports:
      - '3000:3000'

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx/confs/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/private
    ports:
      - "8080:8080"
      - "443:443"
